### ISSUE TITLE
Feature: User can view a single day with its liturgical celebration details

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/ajax-project#1]
## ⚙️ Feature

> ##### Users will be able to view a single day with the days liturgical celebration details.

## 📐 Plan

Create a page which displays specific information about the daily Catholic Liturgy

## ✅ Task List

- [x] add google fonts cormorant, cormorant unicase, cormorant upright weights 400, 700, 500
- [x] create a row for weekday
- [x] create a row for the title of the page, the image and the date
- [x] create a row for the subtext in the bottom left
- [x] add the image source to the html
- [x] create the CSS layout and design for the page.
- [x] DOM query for the text content for the date, page title, and subtext at the bottom of the page.
- [x] GET the data from the API and console.log it
- [x] once you get the data, change the text content of the DOM elements to contain the data provided in the API
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

## 🖼️ Wireframes

<img width="227" alt="Screen Shot 2022-04-18 at 5 27 43 PM" src="https://user-images.githubusercontent.com/96838616/163897225-da9ca9a0-f0f3-4bf2-892d-b3178c1905e6.png">
<img width="878" alt="Screen Shot 2022-04-18 at 5 27 51 PM" src="https://user-images.githubusercontent.com/96838616/163897227-200a8240-30ec-45c1-be1b-de0f5455dc88.png">
