### ISSUE TITLE
Feature: User can view other months past or future

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/ajax-project#14]
## ⚙️ Feature

> ##### Users will be able to view past or present months in the web page.

## 📐 Functionality

> ##### When clicking the right arrow it will advance to the next month, when using the left arrow it will return to the previous month.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add the left and right arrows to the calendar.
- [x] add event listeners to each button
- [x] create a global variable with the value of a number
- [x] create a function to increment or decrement this number depending on which button is clicked.
- [x] at each buttonclick call the getCalendarData function with the argument of the number 
- [x] the next calendar will be created as the data loads
- [x] change the id's of each box in the calendar to the number-i  for ex... ( id="4-24")
- [x] when the showdate function is called, split the id at (-)
- [x] get the string '24' and convert it to a number
- [x] call the renderJournalPageDOM with the xhr response at the number.
- [x] create unique id's for the data model
- [x] center the loading icon for mobile
- [x] check button css
- [x] check all functionality
- [x] remove any unnecessary CSS
- [x] fix any bugs. 

## 🖼️ Wireframes

![Screen Shot 2022-04-26 at 4 32 35 PM](https://user-images.githubusercontent.com/96838616/165409545-6e9deaf8-1de2-43cf-9407-9278c545ac67.png)
![Screen Shot 2022-04-26 at 4 32 41 PM](https://user-images.githubusercontent.com/96838616/165409538-5c08e833-6999-4ede-8a25-89fd48e6fb6b.png)
![Screen Shot 2022-04-26 at 4 32 48 PM](https://user-images.githubusercontent.com/96838616/165409541-9d9d2d31-4a77-48c3-b5e7-7505e3ae34f7.png)
![Screen Shot 2022-04-26 at 4 32 54 PM](https://user-images.githubusercontent.com/96838616/165409544-57cbd5a5-d6fd-4159-91db-ae7d4fa8ceb5.png)
