### ISSUE TITLE
Feature: User can see current date on calendar

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/ajax-project#16]
## 📐 Functionality

> ##### When the calendar loads, the user can see what day it is on the title and by the color of the box.

## 🖼️ Wireframes
![Screen Shot 2022-04-28 at 12 37 24 PM](https://user-images.githubusercontent.com/96838616/165832220-76c4a182-5a4d-4bad-bf88-ce329b7bdeee.png)
![Screen Shot 2022-04-28 at 12 36 45 PM](https://user-images.githubusercontent.com/96838616/165832228-1610f0bf-8f77-41a2-8441-c59e67ba3c64.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a new date object
- [x] create an array of every day of the week
- [x] create an array of every month of the year
- [x] get the date
- [x] get the month
- [x] get the day of the week
- [x] get the year
- [x] assign the textcontent to the $monthTitle variable to match the current date 
- [x] call the getMonthCalendar function with the value of the month property in the date object.
- [x] when the calendar is being created, assign the p element with the id that matches the current day to have a a class with the background color of #F0FBFF 
- [x] fix all bugs
- [x] remove any unnecessary CSS styling
