### ISSUE TITLE
Feature: User can add a journal entry for a particular day.

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/ajax-project#2]
## ⚙️ Feature

> ##### User can add a journal entry for a particular day.

## 📐 Plan

Create a responsive form that allows users to store an image URL with a journal entry for a specific day

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a HTML form 
- [x] give the form a `div[data-view="entry-form"]` 
- [x] create a text area 
- [x] create an input for the photoURL
- [x] put a font-awesome button for the submit
- [x] style the CSS 
- [x] query the form in the DOM
- [x] listen for the input event for the photo and update the photo source to the URL provided
- [x] listen for the submit event
- [x] create a data model in data.js for the journal entry
- [x] in the submit event store the entry number, the date of the entry, and the content in the data model
- [x] save the data model in local storage
- [x] hide the form from view after the submit
- [x] display the new text content

## 🖼️ Wireframes

<img width="747" alt="Screen Shot 2022-04-18 at 5 46 10 PM" src="https://user-images.githubusercontent.com/96838616/163898599-edc9bef7-d02a-44bd-a39e-f2f0c97f0d21.png">
<img width="747" alt="Screen Shot 2022-04-18 at 5 46 21 PM" src="https://user-images.githubusercontent.com/96838616/163898605-b8d2813e-edc3-4138-998b-ff4e8a052bf5.png">
<img width="241" alt="Screen Shot 2022-04-18 at 5 45 45 PM" src="https://user-images.githubusercontent.com/96838616/163898607-576ec591-7d1f-4cab-a7d4-f08c2759978b.png">
<img width="241" alt="Screen Shot 2022-04-18 at 5 45 53 PM" src="https://user-images.githubusercontent.com/96838616/163898614-d15b036f-5eda-4c63-9bad-1d338c9b4a5d.png">
<img width="241" alt="Screen Shot 2022-04-18 at 5 45 49 PM" src="https://user-images.githubusercontent.com/96838616/163898611-7f7f5560-53c7-4c67-87e1-6799be6bbb74.png">
<img width="747" alt="Screen Shot 2022-04-18 at 5 46 30 PM" src="https://user-images.githubusercontent.com/96838616/163898613-2a67a75b-f40f-452b-88e4-7b54f9280dd9.png">
