### ISSUE TITLE
Feature: User can view the current month with its liturgical celebrations

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/ajax-project#3]
## ⚙️ Feature

> #####  User can view the liturgical celebrations of the Catholic Church for the current month

## 📐 Plan

Create a calendar for the month which displays all the feast days

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a calendar in HTML for April
- [x] give each box a name or class for the day of the week
- [x] style the calendar in css accordingly
- [x] get the API for the current month
- [x] query the calendar in the DOM
- [x] set the text content accordingly
- [x] add an arrow to the entries page to toggle from the calendar to the date. 
- [x] remove the calendar from HTML
- [x] make a function to render the calendar in the DOM for the current month

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 10 23 26 AM](https://user-images.githubusercontent.com/96838616/163847154-e8420f62-74be-4c07-b68f-15b6888b234e.png)
![Screen Shot 2022-04-19 at 5 14 55 PM](https://user-images.githubusercontent.com/96838616/164121521-09f72ba8-549e-4399-b1fc-cd8b42b7f7d6.png)

![Screen Shot 2022-04-18 at 10 24 17 AM](https://user-images.githubusercontent.com/96838616/163847256-7a52b3f7-f91a-434e-9d8c-b8f6f2cfc949.png)
![Screen Shot 2022-04-18 at 10 24 22 AM](https://user-images.githubusercontent.com/96838616/163847274-c6aa5b76-e031-4636-93fe-19ad5bb377c4.png)
