### ISSUE TITLE
Feature: User can edit their Journal entry

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/ajax-project#4]
## ⚙️ Feature

> ##### User can edit their Journal entry

## 📐 Plan

Create a responsive edit button that allows the user to edit their journal entry and save it again.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] get pencil icon in font awesome
- [x] create styling for icon 
- [x]  create icon in the DOM tree for the journal notes
- [x] add a click event to the pencil icon
- [x] create a function to edit the journal entry
- [x] the function will need to create a new DOM tree with the form 
- [x] the form will need to be filled with the data from the data model
- [x] add the object to data.editing
- [x] the new page will replace the old one
- [x] the user will be able to edit the form with the information in it
- [x] when the submit is fired check if data.editing is null
- [x] if its not then using a loop find the matching id from editing in the data.entries
- [x] reassign the. properties with the new data
- [x] recreate the journal page and replace the old page with the new one. 
- [x] check to make sure everything is saving correctly in local storage and in the data model
- [x] remove any unnecessary styling or code
- [x] fix all errors

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 10 25 39 AM](https://user-images.githubusercontent.com/96838616/163847595-5312a2ed-840e-447e-a832-378def8187f1.png)
![Screen Shot 2022-04-18 at 10 25 45 AM](https://user-images.githubusercontent.com/96838616/163847597-ad5d65d9-a67d-42ff-87b7-455852c80414.png)
![Screen Shot 2022-04-18 at 10 25 51 AM](https://user-images.githubusercontent.com/96838616/163847599-41e45270-5947-42c6-b4ed-70cc329bc4fa.png)
![Screen Shot 2022-04-18 at 10 25 27 AM](https://user-images.githubusercontent.com/96838616/163847600-2f18bc9f-7ceb-403a-ac50-861f85f7fbc9.png)
![Screen Shot 2022-04-18 at 10 25 31 AM](https://user-images.githubusercontent.com/96838616/163847602-244ab1c1-795c-4478-a63f-603ccf85dda5.png)
![Screen Shot 2022-04-18 at 10 27 30 AM](https://user-images.githubusercontent.com/96838616/163847725-e2334bda-a770-44ee-a5b4-4f60b0d852b0.png)
