### ISSUE TITLE
Feature: User can delete their journal entry

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/ajax-project#5]
## ⚙️ Feature

> ##### User can delete their journal entry

## 📐 Plan

Create a responsive delete button that removes the saved information from the browser and local storage and resets the original form

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create a delete button
- [x] style it in css
- [x] make the button in the DOM tree in the edit function
- [x] add an event listener to the button
- [x] create the modal with two buttons cancel will hide the modal, delete will delete the entry
- [x] add event listeners to both the buttons
- [x] create a function to remove the entry
- [x] find the entry by id in the data.entries and delete it
- [x] call the createDOMTree function
- [x] create a form page in the DOM tree and replace the previous page with the new form. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 10 29 32 AM](https://user-images.githubusercontent.com/96838616/163848402-bccb8520-8f6c-4d58-88d2-0c90388b4dc6.png)
![Screen Shot 2022-04-18 at 10 29 38 AM](https://user-images.githubusercontent.com/96838616/163848405-babb5563-fc5d-44d7-beef-ec293b63e86e.png)
![Screen Shot 2022-04-18 at 10 29 46 AM](https://user-images.githubusercontent.com/96838616/163848408-97a85c96-387d-4ad7-96c2-52a8548942d8.png)
![Screen Shot 2022-04-18 at 10 29 53 AM](https://user-images.githubusercontent.com/96838616/163848409-af241cbc-b797-4fa8-b97f-f888950c5622.png)

![Screen Shot 2022-04-18 at 10 32 00 AM](https://user-images.githubusercontent.com/96838616/163848426-41e14f7a-f7e5-4ed1-a4d0-031db1a04a9b.png)
![Screen Shot 2022-04-18 at 10 30 37 AM](https://user-images.githubusercontent.com/96838616/163848429-85f688a8-3a9f-44bf-9edd-87a671dd5fa4.png)
![Screen Shot 2022-04-18 at 10 30 28 AM](https://user-images.githubusercontent.com/96838616/163848430-8075d938-7897-4e1f-84ee-c38542aca3f7.png)
![Screen Shot 2022-04-18 at 10 30 04 AM](https://user-images.githubusercontent.com/96838616/163848432-a3e5aec2-bbde-4e6b-8f51-18f60512158c.png)
